/** Labels em português para campos das collections de Dados. */
export const FIELD_LABELS = {
  // comuns
  id: 'ID',
  status: 'Status',
  sort: 'Ordem',
  date_created: 'Data de criação',
  date_updated: 'Data de atualização',
  created_date: 'Data de criação',
  email: 'E-mail',
  name: 'Nome',
  last_name: 'Sobrenome',
  first_name: 'Nome',
  cpf: 'CPF',
  rg: 'RG',
  birth_date: 'Data de nascimento',
  gender: 'Gênero',
  nationality: 'Nacionalidade',
  marital_status: 'Estado civil',
  mobile_number: 'Celular',
  phone: 'Telefone',
  street: 'Rua',
  street_number: 'Número',
  complement: 'Complemento',
  neighborhood: 'Bairro',
  city: 'Cidade',
  state: 'Estado',
  cep: 'CEP',
  address: 'Endereço',
  avatar_url: 'URL do avatar',
  user_code: 'Código do usuário',
  tags: 'Etiquetas',
  type: 'Tipo',
  price: 'Preço',
  donation: 'Doação',
  observations: 'Observações',
  message: 'Mensagem',
  active: 'Ativo',
  color: 'Cor',

  // users / associados
  associate_name: 'Nome do associado',
  associate_last_name: 'Sobrenome do associado',
  associate_rg_issuer: 'Órgão emissor do RG',
  associate_cpf: 'CPF do associado',
  associate_rg: 'RG do associado',
  associate_birth_date: 'Data de nascimento',
  associate_status: 'Fase do cadastro',
  email_account: 'E-mail da conta',
  account_password: 'Senha da conta',
  proof_of_address: 'Comprovante de endereço',
  reason_treatment_text: 'Motivo do tratamento',
  responsible_type: 'Tipo de responsável',
  rg_proof: 'Comprovante de RG',
  prescription: 'Receita',
  responsible_code: 'Código do responsável',
  documents_folder_id: 'Pasta de documentos',
  rg_patient_proof: 'Comprovante de RG do paciente',
  patient_user_code: 'Código do paciente',
  adhesion_term: 'Termo de adesão',
  invalid_fields: 'Campos inválidos',
  ciap_codes: 'Códigos CIAP',
  preferred_products: 'Produtos preferidos',
  date_prescription: 'Data da receita',
  annotations: 'Anotações',
  handbook: 'Prontuário',
  prescriber: 'Prescritor',
  delivery_address: 'Endereço de entrega',
  prescriber_code: 'Código do prescritor',
  session_token: 'Token de sessão',
  session_expires: 'Expiração da sessão',
  last_activity: 'Última atividade',
  is_session_active: 'Sessão ativa',
  password_reset_token: 'Token de redefinição de senha',
  password_reset_expires: 'Expiração do token de senha',

  // system_users
  permissions: 'Permissões',
  password: 'Senha',
  pix_key: 'Chave PIX',
  commission_value: 'Valor da comissão',
  transactions: 'Transações',
  commission_total: 'Total de comissão',
  utalk_id: 'ID Utalk',
  utalk_token: 'Token Utalk',
  internal_code: 'Código interno',

  // orders
  total: 'Total',
  payment_method: 'Forma de pagamento',
  tracking_code: 'Código de rastreio',
  delivery_price: 'Frete',
  order_code: 'Código do pedido',
  items: 'Itens',
  discount: 'Desconto',
  details: 'Detalhes',
  payment_link: 'Link de pagamento',
  user: 'Usuário (ID)',
  carrier_order_code: 'Código da transportadora',
  payment_code: 'Código de pagamento',
  order_notes: 'Notas do pedido',
  delivery_notes: 'Notas de entrega',
  whatsapp_message: 'Mensagem WhatsApp',
  payment_date: 'Data do pagamento',
  custom_payment: 'Pagamento personalizado',
  production_owner: 'Responsável pela produção',
  tracking_code_date: 'Data do código de rastreio',
  last_tracking_date: 'Última atualização de rastreio',
  address_validation: 'Validação de endereço',
  created_by_user_code: 'Criado por (código)',

  // partners
  commission_transactions: 'Transações de comissão',
  is_favorite: 'Favorito',
  contest_reports: 'Relatórios de contestação',

  // products
  user_created: 'Criado por',
  user_updated: 'Atualizado por',
  sku: 'SKU',
  unit: 'Unidade',
  concentration: 'Concentração',
  amount: 'Quantidade',
  category: 'Categoria',
  photo: 'Foto',
  batch: 'Lote',

  // professionals
  services_description: 'Descrição dos serviços',
  specialty: 'Especialidade',
  is_prescriber: 'É prescritor',
  is_collaborator: 'É colaborador',
  professional_code: 'Código do profissional',
  fingerprint: 'Impressão digital',
  met_us: 'Como nos conheceu',
  recipient_id: 'ID do recebedor',
  donation_balance: 'Saldo de doação',
  calendar_id: 'ID do calendário',

  // reception
  option1: 'Opção 1',
  option2: 'Opção 2',
  is_associate: 'É associado',
  code: 'Código',
  chat_id: 'ID do chat',
  associate_code: 'Código do associado',
  patient_name: 'Nome do paciente',
  attendant: 'Atendente',
  completion_reason: 'Motivo de conclusão',
  at: 'Em',
  full_name: 'Nome completo',
  fullname: 'Nome completo',

  // reports
  report_code: 'Código do relatório',
  query_config: 'Configuração da consulta',
  sql_query: 'Consulta SQL',
  dashboard_queries: 'Consultas do dashboard',
  layout_positions: 'Posições do layout',
  chart_config: 'Configuração do gráfico',
  created_by: 'Criado por',
  column_maps: 'Mapeamento de colunas',
  embedded_report_codes: 'Códigos de relatórios embutidos',
  favorites: 'Favoritos',

  // services
  professional_id: 'ID do profissional',
  associate_user_code: 'Código do associado',
  associate_email: 'E-mail do associado',
  professional_name: 'Nome do profissional',
  event_link: 'Link do evento',
  consultation_date: 'Data da consulta',
  event_id: 'ID do evento',
  price_paid: 'Preço pago',
  booking_group_code: 'Código do grupo de agendamento',
  professional_email: 'E-mail do profissional',
  service_code: 'Código do serviço',
  payment_type: 'Tipo de pagamento',
  payment_info: 'Informações de pagamento',

  // tags
  tag: 'Etiqueta',
  contexts: 'Contextos',
};

/**
 * Label em português para um campo. Fallback: snake_case → Title Case.
 */
export function fieldLabel(field) {
  if (!field) return '';
  if (FIELD_LABELS[field]) return FIELD_LABELS[field];
  const pretty = String(field).replace(/_/g, ' ');
  return pretty.charAt(0).toUpperCase() + pretty.slice(1);
}
