'use strict';

/**
 * Inventário canônico do contrato de negócio da API.
 * Usado por contract/api-structure.test.js
 */
const { TARGET_TABLES } = require('../schema/collections');
const { OPERATORS } = require('../query/parseFilter');
const { MODULE_NAMES } = require('../routes/modules');

const ERROR_CODES = [
  'VALIDATION_ERROR',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'UNKNOWN_COLLECTION',
  'CONFLICT',
  'RATE_LIMITED',
  'MODULE_DISABLED',
  'INTERNAL_ERROR',
  'INVALID_CREDENTIALS',
  'USER_INACTIVE',
  'AUTH_CONFLICT',
  'ACCOUNT_EXISTS',
  'ACCOUNT_IN_PROGRESS',
  'PHASE_LOCKED',
  'TERMS_MODULE_IN_DEVELOPMENT',
  'CONTRACT_ALREADY_COMPLETED',
  'CONTRACT_NOT_PENDING',
  'TOKEN_INVALID',
  'SIGNATURE_REQUIRED',
  'CONSENT_REQUIRED',
  'TEMPLATE_NOT_PUBLISHED',
  'TEMPLATE_INVALID_VARIABLES',
  'PDF_RENDER_FAILED',
  'LAST_ADMIN',
  'CONFIG_ERROR',
  'TOTAL_MISMATCH',
  'INSUFFICIENT_STOCK',
  'PRODUCT_NOT_FOUND',
  'CONFIG_INCOMPLETE',
  'CREDENTIAL_MISSING',
  'CREDENTIAL_INVALID',
  'FREIGHT_NO_QUOTE',
  'LABEL_NOT_ALLOWED',
  'OAUTH_REQUIRED',
  'SCHEDULING_DISABLED',
  'CALENDAR_NOT_CONFIGURED',
  'CALENDAR_NOT_FOUND',
  'CALENDAR_FORBIDDEN',
  'EVENT_NOT_FOUND',
  'EVENT_DATE_CONFIRMATION_REQUIRED',
  'GOOGLE_API_ERROR',
  'GOOGLE_VALIDATION_ERROR',
  'GOOGLE_CONFLICT',
];

const AUTH_ROUTES = [
  ['POST', '/auth/login'],
  ['POST', '/auth/logout'],
  ['POST', '/auth/forgot-password'],
  ['POST', '/auth/reset-password'],
  ['GET', '/auth/me'],
  ['POST', '/auth/tokens'],
  ['GET', '/auth/tokens'],
  ['DELETE', '/auth/tokens/:id'],
  ['POST', '/auth/associate/register-email'],
  ['POST', '/auth/associate/login'],
  ['POST', '/auth/associate/logout'],
  ['GET', '/auth/associate/me'],
  ['POST', '/auth/associate/forgot-password'],
  ['POST', '/auth/associate/reset-password'],
  ['GET', '/auth/system-invite/preview'],
  ['POST', '/auth/system-invite/accept'],
];

const DOMAIN_ROUTES = [
  ['GET', '/users'],
  ['GET', '/users/exists'],
  ['GET', '/users/search'],
  ['GET', '/users/by-code/:user_code'],
  ['POST', '/users'],
  ['PATCH', '/users/me'],
  ['GET', '/users/me/patients'],
  ['POST', '/users/me/patients'],
  ['PATCH', '/users/me/patients/:id'],
  ['GET', '/users/me/documents/status'],
  ['POST', '/users/me/advance'],
  ['POST', '/users/me/complete'],
  ['PATCH', '/users/:id'],
  ['GET', '/users/:id/patients'],
  ['POST', '/users/:id/handbook'],
  ['POST', '/orders'],
  ['GET', '/orders'],
  ['GET', '/orders/facets'],
  ['GET', '/orders/status-config'],
  ['POST', '/orders/bulk'],
  ['PATCH', '/orders/:id'],
  ['GET', '/orders/by-user/:userCode'],
  ['PATCH', '/orders/:id/status'],
  ['PATCH', '/orders/:id/production'],
  ['POST', '/orders/:id/payment'],
  ['GET', '/orders/stats'],
  ['DELETE', '/orders/:id'],
  ['POST', '/freight/quote'],
  ['GET', '/freight/service-options'],
  ['GET', '/freight/default-option'],
  ['PUT', '/freight/default-option'],
  ['GET', '/admin/external-services'],
  ['GET', '/admin/external-services/:service'],
  ['PATCH', '/admin/external-services/:service'],
  ['GET', '/admin/external-services/:service/credentials'],
  ['PUT', '/admin/external-services/:service/credentials'],
  ['DELETE', '/admin/external-services/:service/credentials/:fieldKey'],
  ['POST', '/admin/external-services/:service/test'],
  ['GET', '/admin/storage'],
  ['PUT', '/admin/storage'],
  ['POST', '/admin/storage/test'],
  ['POST', '/admin/storage/activate'],
  ['GET', '/admin/sample-data'],
  ['DELETE', '/admin/sample-data'],
  ['GET', '/admin/system-errors/summary'],
  ['GET', '/admin/system-errors/top'],
  ['GET', '/admin/system-errors'],
  ['GET', '/admin/system-errors/:errorHash/samples'],
  ['POST', '/admin/system-errors/resolve'],
  ['POST', '/system-errors'],
  ['GET', '/admin/web-vitals/summary'],
  ['GET', '/admin/web-vitals/series'],
  ['GET', '/admin/web-vitals/by-page'],
  ['GET', '/admin/cache'],
  ['PATCH', '/admin/cache'],
  ['POST', '/admin/cache/clear'],
  ['GET', '/cache/status'],
  ['POST', '/cache/clear'],
  ['POST', '/web-vitals'],
  ['POST', '/services'],
  ['GET', '/services'],
  ['PATCH', '/services/:id'],
  ['GET', '/services/by-professional/:id'],
  ['GET', '/services/exists'],
  ['GET', '/reception/form-schema'],
  ['POST', '/reception/public'],
  ['GET', '/reception/status-counts'],
  ['GET', '/reception/attendants'],
  ['POST', '/reception'],
  ['PATCH', '/reception/:id/complete'],
  ['PATCH', '/reception/:id/attendant'],
  ['PATCH', '/reception/:id/status'],
  ['PATCH', '/reception/:id/link'],
  ['PATCH', '/reception/:id/unlink'],
  ['GET', '/activity'],
  ['GET', '/activity/mine'],
  ['GET', '/activity/mine/unread-count'],
  ['POST', '/activity/mine/read'],
  ['PATCH', '/products/:id/batch'],
  ['POST', '/products/sync-batches'],
  ['GET', '/products/export.csv'],
  ['POST', '/products/import/validate'],
  ['POST', '/products/import'],
  ['GET', '/products/:id/movements'],
  ['POST', '/products/:id/stock'],
  ['GET', '/institutional-clients'],
  ['GET', '/institutional-clients/search'],
  ['GET', '/institutional-clients/by-code/:client_code'],
  ['GET', '/institutional-clients/:id'],
  ['GET', '/institutional-clients/:id/history'],
  ['POST', '/institutional-clients'],
  ['PATCH', '/institutional-clients/:id'],
  ['DELETE', '/institutional-clients/:id'],
  ['GET', '/professionals'],
  ['PATCH', '/professionals/:id/donation-balance'],
  ['POST', '/reports'],
  ['POST', '/reports/:id/run'],
  ['POST', '/reports/:id/favorite'],
  ['GET', '/analytics/associates'],
  ['GET', '/analytics/services'],
  ['GET', '/analytics/orders'],
  ['GET', '/analytics/reception'],
  ['GET', '/tags'],
  ['GET', '/system-users'],
  ['POST', '/system-users'],
  ['POST', '/system-users/:id/resend-invite'],
  ['GET', '/system-users/:id'],
  ['PATCH', '/system-users/:id'],
  ['DELETE', '/system-users/:id'],
  ['GET', '/files'],
  ['POST', '/files'],
  ['GET', '/files/:id'],
  ['GET', '/files/:id/download'],
  ['DELETE', '/files/:id'],
  ['POST', '/files/:id/attach'],
  ['DELETE', '/files/:id/attach'],
  ['GET', '/search'],
  ['GET', '/health'],
  ['GET', '/modules'],
  ['GET', '/doc-sign/status'],
  ['GET', '/doc-sign/templates'],
  ['POST', '/doc-sign/templates'],
  ['GET', '/doc-sign/templates-logos'],
  ['POST', '/doc-sign/templates/reset-defaults'],
  ['POST', '/doc-sign/templates/:kind/reset'],
  ['GET', '/doc-sign/templates/:kind'],
  ['PUT', '/doc-sign/templates/:kind/draft'],
  ['POST', '/doc-sign/templates/:kind/publish'],
  ['GET', '/doc-sign/templates/:kind/sample-variables'],
  ['POST', '/doc-sign/templates/:kind/preview-pdf'],
  ['POST', '/doc-sign/contracts'],
  ['POST', '/doc-sign/contracts/:id/resend-email'],
  ['GET', '/doc-sign/contracts'],
  ['GET', '/doc-sign/contracts/me'],
  ['GET', '/doc-sign/contracts/:id'],
  ['DELETE', '/doc-sign/contracts/:id'],
  ['GET', '/doc-sign/sign/:token'],
  ['POST', '/doc-sign/sign/:token/view'],
  ['POST', '/doc-sign/sign/:token/complete'],
  ['POST', '/terms/contracts'],
  ['GET', '/terms/status'],
  ['GET', '/config/public'],
  ['GET', '/config/systems'],
  ['GET', '/config'],
  ['POST', '/config'],
  ['GET', '/config/:id'],
  ['PATCH', '/config/:id'],
  ['DELETE', '/config/:id'],
  ['POST', '/config/:id/clear'],
  ['GET', '/admin/schema'],
  ['GET', '/admin/roles'],
];

const ITEMS_METHODS = ['GET', 'POST', 'PATCH', 'DELETE'];

module.exports = {
  COLLECTIONS: TARGET_TABLES,
  QUERY_OPERATORS: [...OPERATORS],
  ERROR_CODES,
  AUTH_ROUTES,
  DOMAIN_ROUTES,
  ITEMS_METHODS,
  MODULE_NAMES,
};
