'use strict';

/**
 * Inventário canônico do contrato de negócio da API.
 * Usado por contract/api-structure.test.js
 */
const { TARGET_TABLES } = require('../schema/collections');
const { OPERATORS } = require('../query/parseFilter');
const { MODULE_NAMES } = require('../routes/modules');

const ERROR_CODES = [
  'VALIDATION_ERROR',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'UNKNOWN_COLLECTION',
  'CONFLICT',
  'RATE_LIMITED',
  'MODULE_DISABLED',
  'INTERNAL_ERROR',
  'INVALID_CREDENTIALS',
  'USER_INACTIVE',
  'AUTH_CONFLICT',
  'ACCOUNT_EXISTS',
  'ACCOUNT_IN_PROGRESS',
  'PHASE_LOCKED',
  'TERMS_MODULE_IN_DEVELOPMENT',
  'LAST_ADMIN',
  'CONFIG_ERROR',
  'TOTAL_MISMATCH',
  'CONFIG_INCOMPLETE',
  'CREDENTIAL_MISSING',
  'CREDENTIAL_INVALID',
  'FREIGHT_NO_QUOTE',
  'LABEL_NOT_ALLOWED',
];

const AUTH_ROUTES = [
  ['POST', '/auth/login'],
  ['POST', '/auth/logout'],
  ['GET', '/auth/me'],
  ['POST', '/auth/tokens'],
  ['GET', '/auth/tokens'],
  ['DELETE', '/auth/tokens/:id'],
  ['POST', '/auth/associate/register-email'],
  ['POST', '/auth/associate/login'],
  ['POST', '/auth/associate/logout'],
  ['GET', '/auth/associate/me'],
  ['POST', '/auth/associate/forgot-password'],
  ['POST', '/auth/associate/reset-password'],
];

const DOMAIN_ROUTES = [
  ['GET', '/users'],
  ['GET', '/users/exists'],
  ['GET', '/users/search'],
  ['GET', '/users/by-code/:user_code'],
  ['POST', '/users'],
  ['PATCH', '/users/me'],
  ['GET', '/users/me/patients'],
  ['POST', '/users/me/patients'],
  ['PATCH', '/users/me/patients/:id'],
  ['GET', '/users/me/documents/status'],
  ['POST', '/users/me/advance'],
  ['POST', '/users/me/complete'],
  ['PATCH', '/users/:id'],
  ['GET', '/users/:id/patients'],
  ['POST', '/users/:id/handbook'],
  ['POST', '/orders'],
  ['GET', '/orders'],
  ['GET', '/orders/facets'],
  ['GET', '/orders/status-config'],
  ['POST', '/orders/bulk'],
  ['PATCH', '/orders/:id'],
  ['GET', '/orders/by-user/:userCode'],
  ['PATCH', '/orders/:id/status'],
  ['PATCH', '/orders/:id/production'],
  ['POST', '/orders/:id/payment'],
  ['GET', '/orders/stats'],
  ['DELETE', '/orders/:id'],
  ['POST', '/freight/quote'],
  ['GET', '/freight/service-options'],
  ['GET', '/freight/default-option'],
  ['PUT', '/freight/default-option'],
  ['GET', '/admin/external-services'],
  ['GET', '/admin/external-services/:service'],
  ['PATCH', '/admin/external-services/:service'],
  ['GET', '/admin/external-services/:service/credentials'],
  ['PUT', '/admin/external-services/:service/credentials'],
  ['DELETE', '/admin/external-services/:service/credentials/:fieldKey'],
  ['POST', '/admin/external-services/:service/test'],
  ['POST', '/services'],
  ['GET', '/services'],
  ['PATCH', '/services/:id'],
  ['GET', '/services/by-professional/:id'],
  ['GET', '/services/exists'],
  ['GET', '/reception/form-schema'],
  ['POST', '/reception/public'],
  ['GET', '/reception/status-counts'],
  ['GET', '/reception/attendants'],
  ['POST', '/reception'],
  ['PATCH', '/reception/:id/complete'],
  ['PATCH', '/reception/:id/attendant'],
  ['PATCH', '/reception/:id/status'],
  ['PATCH', '/reception/:id/link'],
  ['PATCH', '/reception/:id/unlink'],
  ['GET', '/activity'],
  ['GET', '/activity/mine'],
  ['GET', '/activity/mine/unread-count'],
  ['POST', '/activity/mine/read'],
  ['PATCH', '/products/:id/batch'],
  ['POST', '/products/sync-batches'],
  ['GET', '/partners/by-code/:user_code'],
  ['PATCH', '/partners/:id/favorite'],
  ['GET', '/professionals'],
  ['PATCH', '/professionals/:id/donation-balance'],
  ['POST', '/reports'],
  ['POST', '/reports/:id/run'],
  ['POST', '/reports/:id/favorite'],
  ['GET', '/tags'],
  ['GET', '/system-users'],
  ['POST', '/system-users'],
  ['GET', '/system-users/:id'],
  ['PATCH', '/system-users/:id'],
  ['DELETE', '/system-users/:id'],
  ['GET', '/files'],
  ['POST', '/files'],
  ['GET', '/files/:id'],
  ['GET', '/files/:id/download'],
  ['DELETE', '/files/:id'],
  ['POST', '/files/:id/attach'],
  ['DELETE', '/files/:id/attach'],
  ['GET', '/search'],
  ['GET', '/health'],
  ['GET', '/modules'],
  ['POST', '/terms/contracts'],
  ['GET', '/terms/status'],
  ['GET', '/config/public'],
  ['GET', '/config/systems'],
  ['GET', '/config'],
  ['POST', '/config'],
  ['GET', '/config/:id'],
  ['PATCH', '/config/:id'],
  ['DELETE', '/config/:id'],
  ['POST', '/config/:id/clear'],
  ['GET', '/admin/schema'],
  ['GET', '/admin/roles'],
];

const ITEMS_METHODS = ['GET', 'POST', 'PATCH', 'DELETE'];

module.exports = {
  COLLECTIONS: TARGET_TABLES,
  QUERY_OPERATORS: [...OPERATORS],
  ERROR_CODES,
  AUTH_ROUTES,
  DOMAIN_ROUTES,
  ITEMS_METHODS,
  MODULE_NAMES,
};
